### PR TITLE
Fix a malfunction of auto_completion

### PR DESCRIPTION
**Pull request by ihwang**
Delete an unnecessary and mislocated sub-feature that causes the problem in #68.

### CODE REVIEW

**Review by VictoriaElisabet — APPROVED** [review]
Seems to work now

**Review by xopxop — DISMISSED** [review]
It works

**Comment by xopxop** [comment]
https://drive.google.com/file/d/1tbCm7Hb7SThcWPJOsVwTVgiySFxe02Uh/view?usp=sharing
segfault with hidden file

**Comment by xopxop** [comment]
https://drive.google.com/file/d/1a-n8nPMQVp0rx03_viSbqqh-2gXbvF8E/view?usp=sharing
cd ../..
autocompletion wrong directory

**Review by robkle — COMMENTED** [review]
The following auto-completion test from the eval from does not work on my machine:
abc=def
echo $a
Pressing tab does not do anything.
Otherwise, everything else seems to work well.

**Comment by ihwang** [comment]
@robkle 42sh's auto_completion wasn't intended to claim points from the evaluation. It's a kind of replacement for dealing with `\t`in line edition.

**Comment by xopxop** [comment]
1. The hidden directory ./ and ../ should be hidden but it is not
https://drive.google.com/file/d/1g6uzbYJEKR-HlmQS_8g36Ez7s-pXcPIt/view?usp=sharing

If you fix this I will approve the merge request

**Comment by xopxop** [comment]
2. Issue with file have white space, white space should be block by inhibitor \
https://drive.google.com/file/d/1f03_1hVlTcVYwxM-HaXJgTVSvLaDvWYb/view?usp=sharing

It is a small issue, however It is ok for me if you only fix the problem above.

**Review by xopxop — CHANGES_REQUESTED** [review]
The autocompletion shouldnt list the ./ and ../ directory

**Review by xopxop — APPROVED** [review]

**Pull request merged**
