### PR TITLE
105/dudu/job message

### PR DESCRIPTION
**Pull request by xopxop**

### CODE REVIEW

**Review by ihwang — APPROVED** [review]
Sending a signal to a background process and printing a proper message is working well
Here's the example.
```
42sh tango [~/42/42sh_job][1]
> python -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'
[1]   Segmentation fault: 11  python -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'
```

**Review by VictoriaElisabet — APPROVED** [review]
Ok

**Comment by VictoriaElisabet** [comment]
At least to me the message doesn't need to be exatly the same so I think we can leave it like that

**Comment by xopxop** [comment]
Can u give me the example how it print like?

**Review by robkle — APPROVED** [review]

**Pull request merged**
